src/tabletoolbar.js
src/ui/utils.js
src/utils.js
tests/integration.js
tests/tabletoolbar.js

Fix: The `BalloonToolbar` should be enabled for a table content. Link editing should be possible in the table. Closes #28.
----
**Note:** Requires https://github.com/ckeditor/ckeditor5-ui/pull/406 to fix the issue with the link balloon attached to the table instead of a link in the cell.

t/28: The BalloonToolbar should be enabled for a table content

---

src/ui/inserttableview.js
tests/ui/inserttableview.js

Fix: [ClassicEditor] Creating table fails when the toolbar is sticky. Closes #37.

Fix: [ClassicEditor] Creating table fails when the toolbar is sticky.

---

src/tabletoolbar.js
src/ui/utils.js
tests/tabletoolbar.js

Other: Table toolbar shouldn't be displayed when whole table is selected. Closes #36.
---
* none - as agreed in #36 currently all the table toolbar contents are disabled so no need to display it

Changed: Table toolbar shouldn't be displayed when whole table is selected.

---

src/commands/mergecellcommand.js
tests/commands/mergecellcommand.js

Fix: Broken table layout when merging cell with a cell above. Closes #43.
---
- I've refactored the code a bit as the `rowspan` in `tableMap.find()` callback was taken from wrong scope.

Fix: Broken table layout when merging cell with a cell above.

---

src/table.js
src/tableediting.js
tests/manual/table.html
theme/table.css
theme/tableediting.css

Feature: The MVP of table content styles. Moved styles related to the editing to ckeditor5-theme-lark (see #2).
---
* Requires: https://github.com/ckeditor/ckeditor5-theme-lark/pull/176
**Note:** It's an MVP which means we may still improve the styles in the future (doesn't close #2).
* Centered layout similar to default image styles,
* By default the table is **not** full-width because it looks odd when it's 2x2 and spans 1000px
* `min-width` of the table cell + `padding` to make an empty table look more user–friendly; easier to place the caret inside,
* Bold text in header cells to stress their meaning,
* A very slight background of header cells to avoid situations when the body cells have bold text and there's no obvious boundary between the header and the content (also when there's no …

t/2: The MVP of table content styles

---

src/tableui.js
tests/tableui.js

Feature: Added separators to the table UI drop-downs. Closes #24.
---
Requires:
* https://github.com/ckeditor/ckeditor5-ui/pull/407
* https://github.com/ckeditor/ckeditor5-theme-lark/pull/177

t/24: Added separators to the table UI drop-downs

---

src/ui/inserttableview.js
tests/ui/inserttableview.js

Fix: Error thrown when navigating into the table insertion panel using the keyboard. Closes #30.
---
* I've simply removed the error by adding missing dummy methods. The core issue is that this view does not have keyboard support (#22). So I'd fix the error here and implement #22 with proper keyboard support either before or after the initial release.

Fix: Error thrown when navigating into the table insertion panel using the keyboard.

---

theme/table.css

Fix: Selected table's outline should be visible when the table is not being hovered. Closes #50.
---
For the reviewer: worth checking in multiple browsers.

t/50: Selected table's outline should be visible when the table is not being hovered

---

src/converters/downcast.js
src/utils.js
tests/_utils/utils.js
tests/converters/downcast.js
tests/converters/upcasttable.js
tests/manual/table.html
tests/tableediting.js
theme/table.css

Fix: The output HTML should use `<figure>`. Closes #51.
---
* Also changes in theme lark: https://github.com/ckeditor/ckeditor5-theme-lark/tree/t/ckeditor5-table/51.

T/51: Use <figure> for table widget

---

src/commands/inserttablecommand.js
src/tableutils.js
tests/commands/inserttablecommand.js

Fix: Selection should be in the first cell of an inserted table. Closes #61.
---
* Simple fix - I've made `TableUtils#createTable()` return inserted table element so `InsertTableCommand` can set the selection. I don't think that `TableUtils#createTable()` method should set the selection.

Fix: Selection should be in the first cell of an inserted table.

---

src/tableui.js
tests/tableui.js

Feature: Used the switch button to toggle table headers  (see ckeditor/ckeditor5-ui#402).
Also:
* Aligned the `TableUI` to the new API of the `addListToDropdown` helper,
* Updated the tests to consider the `ListItemView` as simply a container for buttons.
---
**A piece of https://github.com/ckeditor/ckeditor5-ui/pull/414.**

t/ckeditor5-ui/402: Used the switch button to toggle table headers

---

src/commands/mergecellcommand.js
tests/commands/mergecellcommand.js

Fix: The `MergeCellCommand` should check if merging cells results in empty row. Closes #16.
---
* The fix is simple but might not go necessarily into upcoming release.
* Also the #47 is a separate issue so this one looks fixed.

Fix: Remove empty row in MergeCellCommand.

---

src/tabletoolbar.js
tests/tabletoolbar.js

Internal: Used UI#update event instead of View#render to attach the UI components.
---
- https://github.com/ckeditor/ckeditor5-core/pull/131

Used UI#update event instead of View#render to attach table UI.

---

src/commands/setheadercolumncommand.js
src/commands/setheaderrowcommand.js
tests/commands/setheadercolumncommand.js
tests/commands/setheaderrowcommand.js

Fix: Switching heading columns/rows off will now behave as expected. Closes #34.
---
* works as expected now :smile:

Fix: Switching heading columns/rows off will now behave as expected.

---

src/commands/inserttablecommand.js
src/tableutils.js
tests/commands/inserttablecommand.js

Other: Table feature should insert table the same way as other widgets. Closes #27.
BREAKING CHANGE: The `TableUtils#createTable()` method now accepts model `Writer` instance instead of `Position`. The method no longer inserts created table to the model - use returned value instead.
---
* Part of: https://github.com/ckeditor/ckeditor5-engine/pull/1545

Unify widget insertion

---

src/converters/upcasttable.js
tests/converters/upcasttable.js

Fix: The upcast conversion now properly parses inline content in table cell into single paragraph. Closes ckeditor/ckeditor5#1246.
---
* The table cell contents are now properly aoutoparagraphed.

Upcast conversion fix.

---

src/converters/upcasttable.js
tests/converters/upcasttable.js

Fix: Skip text nodes between `tr` elements during table upcast. Closes #145.
---
See #145.

Skip text nodes between `tr` elements during table upcast

---

src/tableediting.js
src/utils.js
tests/_utils/utils.js
tests/converters/upcasttable.js
tests/manual/table.js
tests/manual/tableblockcontent.html
tests/manual/tableblockcontent.js
tests/manual/tableblockcontent.md
tests/tableediting.js
tests/tabletoolbar.js

Feature: Introduce images in tables. Closes #99.
---
* Requires changes in
* Widget: https://github.com/ckeditor/ckeditor5-widget/pull/62 (will resolve #98)
* Engine: https://github.com/ckeditor/ckeditor5-engine/pull/1608
* Image: https://github.com/ckeditor/ckeditor5-image/pull/262
* BlockQuote: https://github.com/ckeditor/ckeditor5-block-quote/pull/29
* Constelation of branches is available in [CKEditor 5 branch](https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-table/99).

T/99: Introduce images in tables.

---

src/tabletoolbar.js
src/utils.js
tests/tabletoolbar.js

Other:  Aligned to the new `WidgetToolbarRepository` API. Replaced the `isTableWidgetSelected()` utility with `getSelectedTableWidget()`. Replaced `isTableContentSelected()` with `getTableWidgetAncestor()` (see ckeditor/ckeditor5-widget#60).
BREAKING CHANGE: The `isTableWidgetSelected()` utility has been replaced by `getSelectedTableWidget()` and returns an editing `View` element instead of `Boolean`.
BREAKING CHANGE: The `isTableContentSelected()` utility has been replaced by `getTableWidgetAncestor()` and returns an editing `View` element instead of `Boolean`.
---
This change partially reverts the utility to its functionality before https://github.com/ckeditor/ckeditor5-table/commit/56adacf1c89fafcc941936fccdcd786db01d629f. The inner widget discovery is now on the …

t/ckeditor5-widget/60:  Aligned to the new `WidgetToolbarRepository` API

---

tests/_utils/utils.js
tests/converters/downcast.js

Internal: Renamed the `.ck-widget_selectable` class to `.ck-widget_with-selection-handler` for better semantics (see ckeditor/ckeditor5-widget#66).
---
Requires https://github.com/ckeditor/ckeditor5-widget/pull/67.

t/ckeditor5-widget/66: Renamed the `.ck-widget_selectable` class to `.ck-widget_with-selection-handler`

---

src/converters/table-cell-content-post-fixer.js
tests/converters/table-cell-content-post-fixer.js

Fix: Add check for $text node in table cell content in post-fixer. Closes #134.
---
* As [pointed out by](https://github.com/ckeditor/ckeditor5-table/pull/127#discussion_r221924586) @Reinmar  the table cell can contain a `$text` node - ie created by other features as this is not enforced by schema.

T/134: Wrap $text nodes in paragraphs - table cell content post fixer addition

---

src/converters/downcast.js
tests/converters/downcast.js

Fix: Single paragraphs with attributes inside tableCell will be properly converted in data pipeline.. Closes ckeditor/ckeditor5#1620.
---
* It works but probably some refactor of those converters would be nice.

T/ckeditor5/1620: Fix downcast conversion in data pipeline when converting single paragraph with attributes in table cell.

---

src/tableediting.js
tests/tableediting.js

Fix: Table rows will not be added on tab key press if the associated command is disabled. Closes #185.

Table rows will not be added on tab key press if the associated command is disabled

---

src/converters/tablecell-post-fixer.js
tests/converters/tablecell-post-fixer.js

Fixed: Table cell view post-fixer will not crash if an element inside a cell got attribute and was removed at the same time. Closes #191.

Table cell view post-fixer will not crash if an element inside a cell got attribute and was removed at the same time

---

src/tabletoolbar.js
tests/tabletoolbar.js

Other: Remove deprecated 'table.toolbar' configuration option. Closes #167.
BREAKING CHANGE: `config.table.toolbar` is now removed from code. Use `config.table.contentToolbar`instead.
---
~I remain configuration docs entry for this option. I think there should be some trace that such option existed. However Umberto doesn't mark it properly.~ It was removed as well after review comment.
Related issue ( https://github.com/cksource/umberto/issues/799 )

Remove deprecated configuration option.

---

lang/contexts.json
src/tabletoolbar.js
tests/tabletoolbar.js

Fix: Add `aria-label` for table toolbar.
---
* Requires: ckeditor/ckeditor5-widget#91

Add `aria-label` for table toolbar

---

src/utils.js
tests/_utils/utils.js
tests/converters/downcast.js

Internal: Aligned to the rename in the ckeditor5-widget package ("handler" became "handle", see ckeditor/ckeditor5-widget#99).
---
Requires https://github.com/ckeditor/ckeditor5-widget/pull/110.

t/ckeditor5-widget/99: Aligned to the rename in the ckeditor5-widget package

---

src/commands/mergecellcommand.js

Internal: Set `MergeCellCommand#value` before `#isEnabled` so it is available in `#isEnabled` observable callbacks.

Set MergeCellCommand#value before #isEnabled so it is available in #isEnabled observable callbacks

---

src/commands/mergecellcommand.js
tests/commands/mergecellcommand.js

Fix: Disable horizontal cell merges between header and body cells. Closes ckeditor/ckeditor5#5744.
NOTE: Prevents merging between column header cells and body cells
---
This assumes this is the direction to take on the issue documented here: https://github.com/ckeditor/ckeditor5/issues/5744

Disable horizontal merge between header and body cells.

---

lang/contexts.json
src/tablecellproperties/tablecellpropertiesui.js
src/tablecellproperties/ui/tablecellpropertiesview.js
src/tableproperties.js
src/tableproperties/tablepropertiesui.js
src/tableproperties/ui/tablepropertiesview.js
src/ui/formheaderview.js
src/ui/formrowview.js
src/ui/utils.js
tests/manual/tableproperties.js
tests/tableproperties/tablepropertiesediting.js
tests/tableproperties/tablepropertiesui.js
tests/tableproperties/ui/tablepropertiesview.js
tests/ui/formheaderview.js
tests/ui/utils.js
theme/form.css
theme/formheader.css
theme/formrow.css
theme/tablecellproperties.css
theme/tableform.css
theme/tableproperties.css

Feature: Implemented the table properties form. Closes ckeditor/ckeditor5#6112.
---
[**CI and the constellation**](https://github.com/ckeditor/ckeditor5/tree/i/6112)
* styles for the compact toolbar,
* styles fro the table properties form,
* I found out that we didn't separate wireframe and theme styles in the previous PR so this PR does that
* styles for private components like `FormRowView` and `FormHeaderView`.
`TablePropertiesUI` and `TableCellPropertiesUI` are very similar (same with the views). At first, I wanted to create a base class (classes) for all of them (and/or a tool to help compose them) but then I figured this may not be the best idea because even though at this moment they are very similar, they may diverge in the future and this will be a situation with an …

I/6112: Implemented the table properties form

---

src/converters/downcast.js
tests/_utils/utils.js
tests/converters/downcast.js
tests/converters/table-cell-refresh-post-fixer.js
tests/manual/tickets/6062.html
tests/manual/tickets/6062.js
tests/manual/tickets/6062.md

Fix: Fixed a bug with spellchecking or pasting via the context menu into a table cell crashing the editor. Closes ckeditor/ckeditor5#6062.

Fix a bug with spellchecking used in a table cell crashing the editor

---

src/tablecellproperties/tablecellpropertiesui.js
src/tablecellproperties/ui/tablecellpropertiesview.js
src/tableproperties/tablepropertiesui.js
src/tableproperties/ui/tablepropertiesview.js
src/ui/utils.js
tests/tablecellproperties/tablecellpropertiesui.js
tests/tablecellproperties/ui/tablecellpropertiesview.js
tests/tableproperties/tablepropertiesui.js
tests/tableproperties/ui/tablepropertiesview.js
tests/ui/utils.js
theme/tableform.css

Internal: Table and table cell property form fields should be validated. Closes ckeditor/ckeditor5#6131.
---
Requires:

i/6131: Table and table cell property form fields should be validated

---

src/tablecellproperties/tablecellpropertiesui.js
src/tableproperties/tablepropertiesui.js
tests/tablecellproperties/tablecellpropertiesui.js
tests/tableproperties/tablepropertiesui.js

Fix: Cancelling the table and table cell property forms should not remove a newly created table. Closes ckeditor/ckeditor5#6180.

i/6180: Clicking cancel in a table and a table cell property forms should not remove a newly created table

---

src/commands/utils.js
src/tablecellproperties/commands/tablecellborderwidthcommand.js
src/tablecellproperties/commands/tablecellheightcommand.js
src/tablecellproperties/commands/tablecellpaddingcommand.js
src/tablecellproperties/commands/tablecellpropertycommand.js
src/tablecellproperties/commands/tablecellwidthcommand.js
src/tableproperties/commands/tableborderwidthcommand.js
src/tableproperties/commands/tableheightcommand.js
src/tableproperties/commands/tablepropertycommand.js
src/tableproperties/commands/tablewidthcommand.js
src/ui/utils.js
tests/tablecellproperties/commands/tablecellborderwidthcommand.js
tests/tablecellproperties/commands/tablecellheightcommand.js
tests/tablecellproperties/commands/tablecellpaddingcommand.js
tests/tablecellproperties/commands/tablecellwidthcommand.js
tests/tableproperties/commands/tableborderwidthcommand.js
tests/tableproperties/commands/tableheightcommand.js
tests/tableproperties/commands/tablewidthcommand.js
tests/ui/utils.js

Other: Table and table cell properties commands add default `'px'` unit to numeric values. Closes ckeditor/ckeditor5#6098.
---
I've added this behavior to the commands:
- `TableWidthCommand`
- `TableHeightCommand`
- `TableCellWidthCommand`
- `TableCellHeightCommand`
- `TableCellPaddingCommand`
- `TableCellBorderWidthCommand`
- `TableBorderWidthCommand`
The logic behind this (`addDefaultUnitToNumericValue()` method) is to add default unit only to numeric values. Other values are passed as-is. This is done because other commands also work like this. Value validation is done in the UI.

I/6098: Add `'px'` default unit to commands operationg on lengths.

---

src/tableproperties/tablepropertiesediting.js
tests/_utils/utils.js
tests/tableproperties/commands/tableheightcommand.js
tests/tableproperties/commands/tablewidthcommand.js
tests/tableproperties/tablepropertiesediting.js
theme/table.css

Other: The table's width/height should be downcasted to the `<figure>`. Closes ckeditor/ckeditor5#6186.
---
* Will conflict with #234 because of the same test utility method was upgraded.

I/6186: downcast height/width to <figure>

---

src/converters/tableproperties.js
src/tableproperties/tablepropertiesediting.js
tests/_utils/utils.js
tests/tablecellproperties/tablecellpropertiesediting.js
tests/tableproperties/tablepropertiesediting.js

Internal: Fix style removal conversion. Closes ckeditor/ckeditor5#6183.
---
* There was a "typo" in the converters `writer.removeAttribute()` vs `writer.removeStyle()`.
* More tests aded.

Fix style removal conversion.

---

src/tablecellproperties/ui/tablecellpropertiesview.js
src/tableproperties/ui/tablepropertiesview.js
tests/tablecellproperties/ui/tablecellpropertiesview.js
tests/tableproperties/ui/tablepropertiesview.js

Internal: Setting table/cell style to "none" reset other fields border fields. Closes ckeditor/ckeditor5#6227.

i:6227: Setting table/cell style to "none" reset other fields border fields.

---

src/tableui.js
tests/tableui.js

Other: Implemented lazy loading for the table dropdown. This will reduce editor initialization time. Closes ckeditor/ckeditor5#6193.

Lazy loading for the table dropdown

---

tests/tablecellproperties/tablecellpropertiesediting.js
tests/tableproperties/tablepropertiesediting.js

Tests: Add tests for rgb value of a background-color style. See ckeditor/ckeditor5#6235.
---
* Sub PR for: https://github.com/ckeditor/ckeditor5-engine/pull/1825

6235: Add tests for upcasting background color with rgb value with spaces.

---

src/tablecellproperties/commands/tablecellverticalalignmentcommand.js
src/tablecellproperties/tablecellpropertiesediting.js
src/tablecellproperties/tablecellpropertiesui.js
src/tablecellproperties/ui/tablecellpropertiesview.js
src/tableproperties/tablepropertiesui.js
src/tableproperties/ui/tablepropertiesview.js
src/ui/utils.js
tests/tablecellproperties/tablecellpropertiesediting.js
tests/tablecellproperties/tablecellpropertiesui.js
tests/tablecellproperties/ui/tablecellpropertiesview.js
tests/tableproperties/tablepropertiesui.js
tests/tableproperties/ui/tablepropertiesview.js

Internal: Make default value empty in the model. Closes ckeditor/ckeditor5#6232.
---
* Done - should work. Code style might need improvements and there's a lot of code duplication but this might be a topic for later.

I/6232: Table properties: default value == no value

---

src/tableclipboard.js
src/tableselection.js
src/tableselection/croptable.js
src/tableselection/utils.js
tests/tableclipboard.js
tests/tableselection-integration.js

Feature: Clear table contents on clipboard "cut" and keyboard delete. Closes ckeditor/ckeditor5#6119. Closes ckeditor/ckeditor5#6284. Closes ckeditor/ckeditor5#6301.
---
For the "cut" event handler I had to override (thus duplicate) default `Clipboard` plugin behavior which was removing a single range instead of multi-range selection. This could be simplified by enhancing `model.deleteContent()` (reported here: https://github.com/ckeditor/ckeditor5/issues/6328).

I/6119: Clear table contents on clipboard "cut" and keyboard delete

---

src/commands/utils.js
src/tablecellproperties/commands/tablecellpropertycommand.js
src/ui/utils.js
tests/manual/tableselection.html
tests/manual/tableselection.js
tests/tablecellproperties/commands/tablecellbackgroundcolorcommand.js
tests/tablecellproperties/commands/tablecellbordercolorcommand.js
tests/tablecellproperties/commands/tablecellborderstylecommand.js
tests/tablecellproperties/commands/tablecellborderwidthcommand.js
tests/tablecellproperties/commands/tablecellheightcommand.js
tests/tablecellproperties/commands/tablecellhorizontalalignmentcommand.js
tests/tablecellproperties/commands/tablecellpaddingcommand.js
tests/tablecellproperties/commands/tablecellverticalalignmentcommand.js
tests/tablecellproperties/commands/tablecellwidthcommand.js

Enhancement: Add multi-cell selection to table cell properties UI. Closes ckeditor/ckeditor5#6150.
---
This PR adds the ability to style selected table cells with basic logic for command value. I've extracted a follow for for multi-cell values handling as it looks optional and requires decisions.
@Reinmar: is this follow up OK? https://github.com/ckeditor/ckeditor5/issues/6320

I/6150: Make table cell properties UI aware of mult-cell selection.

---

src/tablecellproperties/commands/tablecellpropertycommand.js
src/tableselection/mouseselectionhandler.js
tests/manual/tableselection.html
tests/manual/tableselection.js
tests/tableselection/mouseselectionhandler.js
theme/table.css
theme/tableselection.css

Other: Improved the look of multi-cell selection. Prevented the selection from starting in the fake selection container (see ckeditor/ckeditor5#6114). Closes ckeditor/ckeditor5#6353.
---
The PR lives on top of https://github.com/ckeditor/ckeditor5-table/pull/253.
This is probably one of many PRs in this issue.
Requires: https://github.com/ckeditor/ckeditor5-theme-lark/pull/268.

i/6114: Improved the look of multi-cell selection. Prevented the selection from starting in the fake selection container

---

src/commands/insertcolumncommand.js
src/commands/insertrowcommand.js
src/commands/utils.js
tests/commands/insertcolumncommand.js
tests/commands/insertrowcommand.js

Other: Added a possibility to insert column or row with multiple selected cells. Closes ckeditor/ckeditor5#6125.
---
As we're going to work with multi-range more, I believe it is a good idea to put a similar method to `getRangeContainedElement` in the `Range` type at some point.
I was unable to quickly find better assertions to asses model selection and data in the same call, so I used two separate method for both.
---
As expected, there are weird scenarios cellspan/rowspan, but at the same time it doesn't look that bad - so I didn't put too much energy into any adjustments in this area.

Added a possibility to insert column or row with multiple selected cells

---

src/tableselection.js
src/tableselection/utils.js
tests/tableselection-integration.js

Internal: Dropped `DeleteCommand` hooks in favor of the `Model#deleteContent()` hook in the `TableSelection` plugin. Improved `deleteContent()` integration tests. Closes ckeditor/ckeditor5#6356.
---
Requires:
* https://github.com/ckeditor/ckeditor5-engine/pull/1827
* https://github.com/ckeditor/ckeditor5-typing/pull/225

i/6356: Dropped `DeleteCommand` hooks in favor of the `Model#deleteContent()`

---

src/commands/insertcolumncommand.js
src/commands/insertrowcommand.js
src/commands/utils.js
src/tableselection/utils.js

Internal: Replaced the `getRangeContainedElement()` helper with `Range#getContainedElement()`. See ckeditor/ckeditor5#6364.
---
Requires: https://github.com/ckeditor/ckeditor5-engine/pull/1829
**Next up**: A PR that cleans up `getSelectedTableCells` helpers by taking advantage of `Range#getContainedElement()` (https://github.com/ckeditor/ckeditor5-table/pull/265).

i/6354: Replaced the getRangeContainedElement() helper with Range#getContainedElement()

---

src/commands/mergecellcommand.js
src/commands/setheadercolumncommand.js
src/commands/utils.js
tests/commands/mergecellcommand.js
tests/commands/utils.js

Fix: Merge left and right commands should be always enabled if the execution does not cross the heading column boundary. Closes ckeditor/ckeditor5#6368.

i/6368: Merge left and right commands should be always enabled if execution does not cross the heading column boundary

---

src/commands/setheadercolumncommand.js
src/commands/setheaderrowcommand.js
tests/commands/setheadercolumncommand.js
tests/commands/setheaderrowcommand.js

Type: Integrated multi cell selection with set column /row header commands. Closes ckeditor/ckeditor5#6127.
---
After this PR the header command state could get a third state - "mixed" because it's possible to make selection where only part of it contains headers:
However to simplify things, I implemented it in a way that command state is true only when all selected cells contain header. Otherwise it's `false`.
~I have based this PR on #266 as this PR adds the API that was useful for this enhancement.~ Rebased onto master, after #265 added API that I was mocking before.

Integrated multi cell selection with set column /row header commands

---

src/converters/tableproperties.js
tests/tableproperties/tablepropertiesediting.js

Fix: Table border styles conversion handler should not throw when it approaches a nested table. Closes ckeditor/ckeditor5#6177.

i/6177: Table border styles conversion handler should not throw when it approaches a nested table

---

src/tableclipboard.js
tests/tableclipboard.js

Internal: Cutting a table with multiple selected cells in readonly mode should not be possible. Closes ckeditor/ckeditor5#6402.

Cutting a table with multiple selected cells in readonly mode should not be possible

---

src/tableutils.js
tests/commands/removerowcommand.js
tests/tableutils.js

Internal: Fixed a case where a table with empty row in model would break remove row command. Closes ckeditor/ckeditor5#6422.
---
Detailed issue explanation can be found here: https://github.com/ckeditor/ckeditor5/issues/6422#issuecomment-598155415
The source of this issue is ckeditor/ckeditor5#3280 but it's a bug that is there for a longer time. This adds additional checks in tableutils, so that broken model like that won't cause issues like that in the future.

Fixed a case where a table with empty row in model would break remove row command

---

src/commands/removecolumncommand.js
src/tableutils.js
tests/commands/removecolumncommand.js
tests/commands/removerowcommand.js
tests/tableutils.js

Fix: Remove row command should not leave empty rows when there are `rowspans` in the structure. Closes ckeditor/ckeditor5#6429.
---
It reverts https://github.com/ckeditor/ckeditor5-table/pull/277 that masked the original issue.

I/6429: Remove row command should not leave empty rows when there are rowspans in the structure

---

src/tableselection.js
tests/tableselection.js

Fix: `TableSelection` plugin should collapse a multi-cell selection when it gets disabled. Closes ckeditor/ckeditor5#6430.

i/6430: `TableSelection` plugin should collapse a multi-cell selection when it gets disabled

---

src/tableselection.js
tests/tableselection-integration.js
tests/tableselection.js

Tests: Tests for a table selection mechanism. Closes ckeditor/ckeditor5#6400.
---
Almost done but two cases are not covered:
It seems like this line of the code could be removed.
Could we simplify the if? Is it required?

Tests for a table selection mechanism

---

src/tablecellproperties/tablecellpropertiesediting.js
tests/tablecellproperties/tablecellpropertiesediting.js

Fix: Horizontal alignment of table cell in RTL content. Closes ckeditor/ckeditor5#6371.
---
Justify icon looks odd for RTL languages - probably should be mirrored?

Fixed horizontal alignment of table cell in RTL content.

---

src/commands/removerowcommand.js
tests/commands/removerowcommand.js

Fix: Remove table row command no longer breaks table heading downcast conversion. Closes ckeditor/ckeditor5#6391.
---
This fix handles current converters and I am not sure if we can fix it better (cheaply that is). The problem was that the attribute conversion on a `<table>` was always executed before `<tableRow>` conversion. The heading attribute downcast converter moves rows from/to `<tbody>` to/from `<thead>` sections. This was breaking mappings and in turn, wrong rows were removed from a view (the model was correct).
This PR makes sure that:
1.  The `headingRows` table model property is calculated once and
2.  Its change is done after removing rows from the table by using `model.enqueueChange()` for this.
~TODO: check if a mapping is re-created in heading converter~ This cannot be …

6391: Table attribute converters must work on target state (after its children conversion proces)

---

src/tableutils.js
tests/tableutils.js

Fix: Inserting table column at the first col-row spanned cell should work properly. Closes ckeditor/ckeditor5#5882.
---

Fix: Inserting table column at first col-row spanned cell should work properly.

---

src/ui/utils.js
tests/ui/utils.js

Other: Position of table cell properties balloon should be in relation to multiple selected cells. Closes ckeditor/ckeditor5#6357.
---

Position of table cell properties balloon should be in relation to multiple selected cells.

---

lang/contexts.json
src/ui/colorinputview.js
src/ui/utils.js
tests/ui/colorinputview.js
tests/ui/utils.js

Fix: Added missing tooltips to the table and table cell properties buttons. Closes ckeditor/ckeditor5#6497.

i/6497: Add tooltips to the table and table cell properties buttons

---

theme/table.css

Other: Added missing border styling after pasting a table outside the editor. Closes ckeditor/ckeditor5#6314.

i/6314: Add missing border styling to the table th and td

---

docs/features/table.md
src/tableui.js
tests/tableui.js

Feature: Implemented a button that merges table cells directly from the table toolbar. Closes ckeditor/ckeditor5#6486.

i/6486: Implemented a button that merges table cells directly from the table toolbar

---

src/tableutils.js
tests/tableutils.js

Fix: Remove row in complex tables now properly move cells from removed rows. Closes ckeditor/ckeditor5#6502.
---
This PR also includes fixes for some issues when not operating on `TableEditing` model (no post-fixer). https://github.com/ckeditor/ckeditor5/issues/6574.
The actual fix is commented below but to fix that I had to understand the logic once again. Thus refactoring to removing all rows at once (this bring also a benefit of fewer operations when removing more than one row.
As a side effect, I've fixed some of the `removeRows()` test as it operated on wrongly created table. See: https://github.com/ckeditor/ckeditor5/issues/6574.

I/6502: Refactor TableUtils.removeRows() logic.

---

src/commands/removecolumncommand.js
src/commands/setheadercolumncommand.js
src/commands/setheaderrowcommand.js
src/utils.js
tests/commands/mergecellscommand.js
tests/commands/removecolumncommand.js
tests/commands/removerowcommand.js
tests/commands/selectrowcommand.js
tests/commands/setheadercolumncommand.js
tests/commands/setheaderrowcommand.js

Other: Introduce `getColumnIndexes()` helper method and properly handle index sorting. Closes ckeditor/ckeditor5#6569. Closes ckeditor/ckeditor5#6544.
---
I don't have a good idea for a merge message as this:
1.  Introduces `getColumnIndexes()` helper method.
2.  Fixes `getRownIndexes()` bug
3.  Fixes other bugs when sorting indexes.
The PR is too big but reviews are long :(

I/6569: Remove array sorting flaws from table code

---

src/commands/removerowcommand.js
src/converters/downcast.js
src/tableutils.js
tests/commands/removerowcommand.js
tests/converters/downcast.js
tests/tableutils.js

Fix: Removing the last header row no longer breaks the table in the editing view. Closes ckeditor/ckeditor5#6437.
---
~The actual fix is in 242a2e0 commit. It turned out that the tests weren't written in the same way as row removing is implemented (df80eec).~ Removing row from a header section involves changing `headingRows` attribute on a table.
The rest of the changes in tests was done due to ckeditor/ckeditor5#6574.

I/6437: Fix - the table breaks after removing a last header row

---

src/tableui.js
tests/tableui.js

Internal: The "Merge cells" split button should always be enabled to improve discoverability of tools in the dropdown. Closes ckeditor/ckeditor5#6631.

i/6631:  The "Merge cells" split button should always be enabled

---

theme/table.css

Fix: Added support for text alignment in the table header, based on the editor's `dir` attribute. Closes ckeditor/ckeditor5#6638.

i/6638: Add support for text alignment in the table header

---

src/commands/mergecellscommand.js
tests/tableselection-integration.js

Other: Merge table cells now set selection in the merged cell before merging other cells into it. Closes ckeditor/ckeditor5#6634. See ckeditor/ckeditor5#6639.
---
*   This is a "work for now" fix because digging the cause of ckeditor/ckeditor5#6639 might take a while.
*   I'm not sure whether to close the original ticket or not. This issue is covered but not fixed.
*   The behaviour is also "wrong" - selection is restored as collapsed in the first table cell.

i/6634: Fix model-selection-range-intersects error in undo after merging two table cells.
