- docs/_snippets/features/build-table-source.js
- docs/_snippets/features/table.html
- docs/_snippets/features/table.js
- docs/api/table.md
- docs/features/table.md
- src/tabletoolbar.js
Docs: Introduce table feature and table API documentation pages. Closes #32.
---
> Docs: Introduce table feature and table API documentation pages.

- docs/features/table.md
- src/commands/insertcolumncommand.js
- src/commands/insertrowcommand.js
- src/commands/inserttablecommand.js
- src/commands/mergecellcommand.js
- src/commands/removecolumncommand.js
- src/commands/removerowcommand.js
- src/commands/setheadercolumncommand.js
- src/commands/setheaderrowcommand.js
- src/commands/splitcellcommand.js
Docs: Improve common API section of a table feature guide. Closes #70.
---
* as suggested I've created a simple list of editor commands with links to classes that implements them. Class docs have the common formula that links to a feature that enables a command in the editor.
> Docs: Improve common API section of a table feature guide.

- src/table.js
Docs: Added crosslinks between API docs and feature description. Closes #71 .
> Docs: Add crosslinks between API docs and feature description.

- tests/_utils/utils.js
Tests: Add docs for test helper methods.
---
* I didn't notice the 2652c2db73797948489aa8e56334f56ad3624535 commit and started to fixing it with proper docs so others can also use those methods in tests.
> Tests: Add docs for test helper methods.

- src/commands/mergecellcommand.js
- tests/commands/insertcolumncommand.js
- tests/commands/insertrowcommand.js
- tests/commands/inserttablecommand.js
- tests/commands/mergecellcommand.js
- tests/commands/removecolumncommand.js
- tests/commands/setheadercolumncommand.js
- tests/commands/setheaderrowcommand.js
- tests/commands/splitcellcommand.js
Fix: Merge cell horizontally should not be possible on overlapped cells. Closes #68.
---
> Fix: Merge cell horizontally should not be possible on overlapped cells.

- tests/tableediting.js
- tests/tabletoolbar.js
Internal: Align code to the API changes (selection post-fixer).
---
* Part of engine PR: https://github.com/ckeditor/ckeditor5-engine/pull/1450
> Internal: Align code to the API changes (selection post-fixer).

- tests/converters/downcast.js
Tests: Update tests to the recent changes in widgets API.
---
* Should be fixed now - using `env.isEdge` stubbing.
> Tests: Update tests to the recent changes in widgets API.

- tests/converters/downcast.js
- tests/tableui.js
Tests: Properly use sinon sandbox in tests.
---
* Fixing  as in related fix: https://github.com/ckeditor/ckeditor5-image/pull/222
> Tests: Properly use sinon sandbox in tests.

- src/utils.js
Internal: Adjusted code to `Writer` to `DowncastWriter` rename in `ckeditor5-engine`.
---
See https://github.com/ckeditor/ckeditor5-engine/issues/1515.
> Adjusted code to 'Writer' to 'DowncastWriter' rename in 'ckeditor5-engine'

- src/converters/downcast.js
- src/converters/tablecell-post-fixer.js
- tests/converters/downcast.js
Internal: Adjusted code after changing `DowncastWriter#rename()` method parametres order in `ckeditor5-engine`.
---
See https://github.com/ckeditor/ckeditor5-engine/pull/1536.
> Adjusted view writer `rename()` call

- docs/features/table.md
Type: Message. Closes #000.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
> Add missing comma in docs

- package.json
- src/tableediting.js
- tests/manual/tableblockcontent.md
- tests/tableediting.js
Fix: Media are no longer allowed inside a table cell. Closes #124.
> Disabled a media in a table

- package.json
- tests/manual/table.js
- tests/table-integration.js
Tests: Added an integration test for ckeditor/ckeditor5#1265.
Requires: https://github.com/ckeditor/ckeditor5-engine/pull/1559.
> Added an integration test for ckeditor/ckeditor5#1265

- src/commands/insertcolumncommand.js
- src/commands/insertrowcommand.js
- src/commands/inserttablecommand.js
- src/commands/mergecellcommand.js
- src/commands/removecolumncommand.js
- src/commands/splitcellcommand.js
- src/tableediting.js
Other: Change to string reference for TableUtils when using editor.plugins.get.
---
* Part of: https://github.com/ckeditor/ckeditor5-core/pull/152
> Change to string reference for TableUtils when using editor.plugins.get.

- src/converters/downcast.js
- src/tableediting.js
- tests/_utils/utils.js
- tests/converters/downcast.js
- tests/tableediting.js
Fix: Make table a block element in the schema for quoting. Closes #126.
---
* Required changes in BlockQuote: https://github.com/ckeditor/ckeditor5-block-quote/pull/27
* Required changes in engine: https://github.com/ckeditor/ckeditor5-engine/pull/1614
* all repos updated for review in main repo: https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5-table/126.
> T/126: Make table block-quotable

- src/converters/downcast.js
Docs: Updated references to `conversionApi`.
---
See https://github.com/ckeditor/ckeditor5-engine/issues/1336.
> Docs: Updated references to `conversionApi`

- tests/table-integration.js
Tests: Adjust tests to recent changes in `DataController`.
---
See https://github.com/ckeditor/ckeditor5-engine/pull/1627.
CI should turn green after https://github.com/ckeditor/ckeditor5-engine/pull/1627 is merged to `master`.
> Tests: Adjust tests to recent changes in DataController

- src/tableediting.js
- tests/tableediting.js
Feature: Allowed media embeds in table cells. Closes #161.
---
Requires https://github.com/ckeditor/ckeditor5-media-embed/pull/73 because otherwise, media will be incredibly small in the table cells.
> t/161: Allowed media embeds in table cells.

- tests/table-integration.js
Tests: Adjustments to changes in `getData()`.
---
Related to https://github.com/ckeditor/ckeditor5-engine/pull/1656. CI should turn green after merging https://github.com/ckeditor/ckeditor5-engine/pull/1656.
> Tests: Adjustments to changes in `getData()`

- src/table.js
Docs: Add editor's config entry with TableConfig.
> Add editor's config entry with TableConfig

- src/commands/setheadercolumncommand.js
- src/commands/setheaderrowcommand.js
- tests/commands/setheadercolumncommand.js
- tests/commands/setheaderrowcommand.js
Internal: change `execute( forceValue )` to `execute( options )`. Closes #207.
> Change execute( forceValue ) to execute( options )

- theme/inserttable.css
Internal: Moved insert table UI theme styles to theme-lark (see ckeditor/ckeditor5#5580).
---
Requires https://github.com/ckeditor/ckeditor5-theme-lark/pull/250.
> i/5580: Moved insert table UI theme styles to theme-lark.

- tests/converters/table-cell-refresh-post-fixer.js
Tests: Fixed tests leaking editor instances / DOM elements. See ckeditor/ckeditor5#6002.
---
For a complete list of PRs see https://github.com/ckeditor/ckeditor5/issues/6002#issuecomment-567834563.
> Fixed tests leaking editor instance / DOM element.

- tests/tableediting.js
Tests: Align test code to the latest changes in selection post-fixer. See ckeditor/ckeditor5-engine#6154.
---
* Sub PR for: https://github.com/ckeditor/ckeditor5-engine/pull/1820
> 6154: Align test code to the latest changes in selection post-fixer.

- src/tablecellproperties/tablecellpropertiesui.js
- src/tableproperties/tablepropertiesui.js
- src/ui/utils.js
- tests/ui/utils.js
Internal: Improve line width validation. Closes ckeditor/ckeditor5#6201.
---
This PR requires:
> Add line width validator for border widths inputs.

- docs/_snippets/features/table.html
Docs: Enhanced the content with emojis in the table feature demo. Closes ckeditor/ckeditor5#6287.
> i/6287: Enhanced the content with emojis in the table feature demo

- src/commands/mergecellcommand.js
- src/commands/removecolumncommand.js
- src/commands/removerowcommand.js
- src/commands/setheadercolumncommand.js
- src/commands/setheaderrowcommand.js
- src/commands/splitcellcommand.js
- src/tableediting.js
- src/tableselection.js
- tests/ui/utils.js
Internal: Used table selection helpers across the package. Closes ckeditor/ckeditor5#6403.
> i/6403: Used table selection helpers across the package

- src/commands/removerowcommand.js
- tests/commands/removerowcommand.js
Type: Fixed a case when removing last row would crash the editor. Closes ckeditor/ckeditor5#6370.
> Fixed a case when removing last row would crash the editor

- theme/table.css
Other: Changed the default background color for the table headers to be slightly darker than table background. Closes ckeditor/ckeditor5#6228.
> i/6228: Change the default background color of the table headers

- src/tableutils.js
- tests/commands/removerowcommand.js
- tests/tableutils.js
Internal: Fixed an issue where remove row command would be enabled when entire column was selected. Closes ckeditor/ckeditor5#6431.
> Fixed an issue where remove row command would be enabled when entire column was selected

- docs/_snippets/features/build-table-source.js
- docs/_snippets/features/table-styling-colors.js
- docs/_snippets/features/table-styling.js
- docs/_snippets/features/table.js
Docs: Added more buttons to the Table snippets toolbar. Closes ckeditor/ckeditor5#6445.
> i/6445: Add more buttons to the Table snippets toolbar

- src/tablenavigation.js
Docs: Updated method visibility. Closes ckeditor/ckeditor5#6670.
---
> Docs: Updated method visibility.
